name: CI
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Acceptance Tests
        run: |
          npm i
          ./node_modules/.bin/codeceptjs run